# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4

trigger:
- main
steps:
- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: '**/*.sln'
    feedsToUse: 'select'
    vstsFeed: 'a423bb44-2fd8-48cc-a7da-cea6ac2452a9'
    restoreDirectory: 'E:\Cache\NugetPackages'
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'hts2v2artifactory'
    targetResolveRepo: 'nuget-virtual'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
    includeEnvVars: true
    packagesDirectory: 'E:\Cache\NugetPackages'