# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
steps:
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'hts2v2artifactory'
    targetResolveRepo: 'nuget-virtual'
    solutionPath: '**/*.sln'
    packagesDirectory: 'E:\Cache\NuGetPackages'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'
