# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- main
steps:
- task: JFrogToolsInstaller@1
  inputs:
    artifactoryConnection: 'hts2v2artifactory'
    cliInstallationRepo: 'jfrog-cli-v2-new'
    installCustomVersion: true
    cliVersion: '2.32.0'
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'hts2v2artifactory'
    targetResolveRepo: 'nuget-virtual'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    buildName: '$(Build.DefinitionName)'
    buildNumber: '$(Build.BuildNumber)'