# ASP.NET
# Build and test ASP.NET projects.
# Add steps that publish symbols, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/aspnet/build-aspnet-4
trigger:
- main
steps:
- task: NuGetToolInstaller@1
  inputs:
    versionSpec: '6.3.0'
- task: JFrogNuGet@1
  inputs:
    command: 'restore'
    artifactoryConnection: 'hts2v2artifacgtory'
    targetResolveRepo: 'nuget-virtual'
    solutionPath: '**/*.sln'
    collectBuildInfo: true
    includeEnvVars: true
    projectKey: nuget

